services:
  quarkus:
    image: dockerfile-nr-jvm:latest
    environment:
      quarkus.datasource.db-kind: mysql
      quarkus.datasource.username: user
      quarkus.datasource.password: password
      quarkus.datasource.url: jdbc:mysql://mysql:3306/db
      quarkus.datasource.jdbc.max-size: 20
      quarkus.hibernate-orm.database.generation: drop-and-create
      quarkus.log.level: INFO
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: