services:
  quarkus:
    image: dockerfile-native-micro:latest
    environment:
      quarkus.datasource.db-kind: mysql
      quarkus.datasource.username: user
      quarkus.datasource.password: password
      quarkus.datasource.reactive.url: mysql://mysql:3306/db
      quarkus.datasource.reactive.max-size: 20
      quarkus.hibernate-orm.database.generation: drop-and-create
      quarkus.log.level: INFO
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on:
      - mysql

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    command: start-dev
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: user
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    command: --init-file /data/application/init.sql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./init.sql:/data/application/init.sql
      - my-db:/var/lib/mysql
volumes:
  my-db: